name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  publish:
    name: Publish
    
    strategy:
      matrix:
        target:
        - '{"rid":"win-x64","os":"windows-latest"}'
        - '{"rid":"win-x86","os":"windows-latest"}'
        - '{"rid":"win-arm","os":"windows-latest"}'
        - '{"rid":"win-arm64","os":"windows-latest"}'
        - '{"rid":"linux-x64","os":"ubuntu-latest"}'
        - '{"rid":"linux-musl-x64","os":"ubuntu-latest"}'
        - '{"rid":"linux-arm","os":"ubuntu-latest"}'
        - '{"rid":"linux-arm64","os":"ubuntu-latest"}'
        - '{"rid":"osx-x64","os":"macos-latest"}'

    needs: [build]
    
    runs-on: ${{ fromJson(matrix.target).os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Publish
      run: dotnet publish ./src/kaiheila-cqhttp.csproj -o ./bin/${{ fromJson(matrix.target).rid }}/publish -c Release -r ${{ fromJson(matrix.target).rid }} --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ fromJson(matrix.target).rid }} Binary
        path: bin/${{ fromJson(matrix.target).rid }}
