name: Build Package

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./src/kaiheila-onebot.csproj --configuration Release --no-restore
    - name: Pack
      run: dotnet pack ./src/kaiheila-onebot.csproj --configuration Release --no-restore
    - name: Copy files
      run: |
        mkdir -p bin/Release/publish
        cp bin/Release/* bin/Release/publish
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kaiheila-onebot-nupkg-${{ github.sha }}
        path: bin/Release/publish
